language: java

sudo: true

before_install:
- cd NoteManager
- chmod +x gradlew
- ./gradlew clean

jdk:
- oraclejdk8

notifications:
email: arnaldo.sgueglia@gmail.com
on_success: never
on_failure: always
  
sudo: required
dist: trusty
group: stable